name = "Klebsiella_oxytoca_Species_Complex_O"
keyword = "kosc_o"
genbank = "Klebsiella_oxytoca_Species_Complex_O_locus_database.gbk"
organism = "Klebsiella oxytoca Species Complex"
taxon = 571
antigen = "Outer lipopolysaccharide"
pathway = "ABC transport-dependent"
prefix = "O"
version = "1.3.0"
id_threshold = 82.5
doi = ["TBD"]
owner = "klebgenomics"
repo = "KoSC-surface-antigen-loci"
branch = "main"
contact = { "Wyres lab, wyreslab.com" = "kaptive.typing@gmail.com" }


[phenotype_logic]

"O11αβ,2αβ" = { loci = ["OL2"], extra_genes = ["gmlA", "gmlB", "gmlC", "wbmV", "wbmW", "wbmX"] }

"O1αβ,2αβ" = { loci = ["OL2"], extra_genes = ["gmlA", "gmlB", "gmlC", "wbbY", "wbbZ"] }
"O11α,2αβ" = { loci = ["OL2"], extra_genes = ["gmlA", "gmlB", "gmlC", "wbmV", "wbmW"] }

"O1α,2αβ" = { loci = ["OL2"], extra_genes = ["gmlA", "gmlB", "gmlC", "wbbY"] }
"O11αβ,2αγ" = { loci = ["OL2"], extra_genes = ["orf8", "wbmV", "wbmW", "wbmX"] }

"O1αβ,2αγ" = { loci = ["OL2"], extra_genes = ["orf8", "wbbY", "wbbZ"] }
"O11αβ,2α" = { loci = ["OL2"], extra_genes = ["wbmV", "wbmW", "wbmX"] }

"O1αβ,2α" = { loci = ["OL2"], extra_genes = ["wbbY", "wbbZ"] }
"O11α,2α" = { loci = ["OL2"], extra_genes = ["wbmV", "wbmW"] }

"O1α,2α" = { loci = ["OL2"], extra_genes = ["wbbY"] }

"O2αβ" = { loci = ["OL2"], extra_genes = ["gmlA", "gmlB", "gmlC"] }
"O2αγ" = { loci = ["OL2"], extra_genes = ["orf8"] }
