name = "Klebsiella_oxytoca_Species_Complex_O"
keyword = "kosc_o"
genbank = "Klebsiella_oxytoca_Species_Complex_O_locus_database.gbk"
organism = "Klebsiella oxytoca Species Complex"
taxon = 571
antigen = "Outer core polysaccharide"
pathway = "Wzm/Wzt-dependent"
prefix = "O"
version = "0.0.0"
id_threshold = 82.5
doi = ["TBD"]
owner = "klebgenomics"
repo = "KoSC-surface-antigen-loci"
branch = "main"
contact = { "Kelly Wyres" = "kaptive.typing@gmail.com" }
