name = "Klebsiella_oxytoca_Species_Complex_K"
keyword = "kosc_k"
genbank = "Klebsiella_oxytoca_Species_Complex_K_locus_database.gbk"
organism = "Klebsiella oxytoca Species Complex"
taxon = 571
antigen = "Capsular polysaccharide"
pathway = "Wzx/Wzy-dependent"
prefix = "K"
version = "1.0.0"
id_threshold = 82.5
doi = ["10.64898/2026.07.16.739023"]
owner = "klebgenomics"
repo = "KoSC-surface-antigen-loci"
branch = "main"
contact = { "Kelly Wyres" = "kaptive.typing@gmail.com" }

[phenotype_logic]
"Capsule null" = { loci = ["KL*"], inactive_genes = ["wza", "wzb", "wzc", "wzx", "wzy", "wcaJ*", "wbaP*"], priority = 100 }
